In [2]:
import numpy as np;
data=np.loadtxt("data.csv",delimiter=",");
x=data[:,0];
y=data[:,1];

In [5]:
from sklearn import model_selection;
x_train,x_test,y_train,y_test=model_selection.train_test_split(x,y);
data=np.array([[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,1],[12,1],[13,1],[14,1],[15,1],[16,1],[17,1]]);
x_train=data[:,0:-1];
y_train=data[:,-1];
print(x_train);
print(y_train);

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]


In [6]:
def fit(x,y):
    num=(x*y).mean()-x.mean()*y.mean();
    den=(x**2).mean()-x.mean()*x.mean();
    m=num/den;
    c=y.mean()-m*(x.mean());
    return m,c;

def pred(x,m,c):
    return (m*x+c);

In [8]:
m,c=fit(x_train,y_train);
ypred=pred(x_train,m,c);
print(ypred);
print(y_test);

[[0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]
 [0.41176471]]
[ 65.10171157  65.28088692  52.68298337  56.87721319  72.24725107
  55.23166089  99.05141484  97.91982104  61.68403752  45.57058882
  78.21151827  50.39267014  75.39287043  63.64239878  59.17148932
  71.54663223  52.72549438  73.68756432  81.43619216  95.53668685
  60.72360244  59.10883927 104.25710159  65.56230126  87.23092513]
